### PR TITLE
feat[isRecordObjectOf]: checks own symbol key properties

### PR DESCRIPTION
**Pull request by Milly**
Contains bug fixes. See below comments.

### CODE REVIEW

**Comment by Milly** [comment]
@lambdalisue 
I have some questions regarding implementation.

`isRecordObjectOf()` and `isRecordOf()` walk the prototype chain of the target object and test all enumerable properties excluding Symbols.

Example:
```ts
class Foo {
  a = "a";
}
const foo = new Foo(); // foo has no own properties.
isRecordOf(is.String)(foo); // true
isRecordOf(is.Number)(foo); // false
```

1. Is this the intended behavior?
2. Should Symbols be tested up the prototype chain as well?

**Comment by lambdalisue** [comment]
> 1. Is this the intended behavior?

No. Because TypeScript's behavior is different

```ts
class Foo {
  a = "a";
}
const _foo: Record<PropertyKey, string> = new Foo();
const _bar: Record<PropertyKey, string> = { a: "a" };
```

CleanShot 2024-08-09 at 12 30 16

> 2. Should Symbols be tested up the prototype chain as well?

Yes. Because TypeScript's behavior is so

```ts
const s = Symbol("symbol");
const _foo: Record<PropertyKey, string> = { a: "a", [s]: "b" };
const _bar: Record<PropertyKey, string> = { a: "a", [s]: 0 };
```

CleanShot 2024-08-09 at 12 32 18

**Comment by Milly** [comment]
@lambdalisue 
I expected the answers to 1 and 2 to be the same.
I wanted to know whether to implement both string keys and symbol keys by "checking only the own properties" (No, No) or by "following the prototype chain and checking everything" (Yes, Yes).

Isn't the second example like this?
```ts
const s = Symbol("s");
class Foo {
  [s] = "a";
}
const foo = new Foo();
isRecordOf(is.String)(foo); // true?
isRecordOf(is.Number)(foo); // false?
```

**Comment by Milly** [comment]
> both string keys and symbol keys by "following the prototype chain and checking everything" (Yes, Yes).

I fixed this behavior like.

**Review by lambdalisue — APPROVED** [review]
LGTM

**Pull request merged**
